-- =================
-- CASO 1 - ADMIN
-- ================
-- Limpieza
BEGIN EXECUTE IMMEDIATE 'DROP ROLE PRY2205_ROL_D'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE PRY2205_ROL_C'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER PRY2205_EFT_CON CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER PRY2205_EFT_DES CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER PRY2205_EFT CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_PROFESIONAL';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_PROFESION';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_ISAPRE';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_TIPO_CONTRATO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_RANGOS_SUELDOS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_CARTOLA_PROFESIONALES';EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_EMPRESA';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_ASESORIA';             EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM SYN_VW_EMPRESAS_ASESORADAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Creacion usuarios
CREATE USER PRY2205_EFT IDENTIFIED BY "EftClaveAA12_2025!"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_DES IDENTIFIED BY "DesClaveBB34_2025!"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_CON IDENTIFIED BY "ConClaveCC56_2025!"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

-- Creacion roles
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_C;

-- Permiso básico para conectarse
GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;

--  Configurar usuario PRY2205_EFT
GRANT CREATE TABLE TO PRY2205_EFT; --crear tablas
GRANT CREATE VIEW TO PRY2205_EFT; -- crear vistas
GRANT CREATE SEQUENCE TO PRY2205_EFT; -- crear secuencias
GRANT CREATE SYNONYM TO PRY2205_EFT; -- crear sinonimos
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT; -- crear sinonimos publicos

-- Configurar rol D
GRANT CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE PROFILE TO PRY2205_ROL_D;
GRANT CREATE USER TO PRY2205_ROL_D;

-- Asignar el rol al usuario de desarrollo
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

-- ===================
-- CASO 1 - USER EFT
-- ===================

SHOW USER;
-- CORRER ESQUEMA

-- como es privado, la limpieza lo ejecuta el owner // opcional
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM SYN_RANGOS_PRIV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
--Sinonimo privado (uso interno del owner) // opcional para ejecutar esquema con sinonimo
CREATE SYNONYM SYN_RANGOS_PRIV FOR PRY2205_EFT.RANGOS_SUELDOS;

-- Sinonimos publicos caso 2
CREATE PUBLIC SYNONYM SYN_PROFESIONAL FOR PRY2205_EFT.PROFESIONAL;
CREATE PUBLIC SYNONYM SYN_PROFESION FOR PRY2205_EFT.PROFESION;
CREATE PUBLIC SYNONYM SYN_ISAPRE FOR PRY2205_EFT.ISAPRE;
CREATE PUBLIC SYNONYM SYN_TIPO_CONTRATO FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE PUBLIC SYNONYM SYN_RANGOS_SUELDOS FOR PRY2205_EFT.RANGOS_SUELDOS;
CREATE PUBLIC SYNONYM SYN_CARTOLA_PROFESIONALES FOR PRY2205_EFT.CARTOLA_PROFESIONALES;

-- Permiso para poder hacer el informe del caso 2 al desarollador
GRANT INSERT, DELETE, SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_D;

-- Permiso para poder ver el informe del caso 2 al consultor
GRANT SELECT ON PRY2205_EFT.CARTOLA_PROFESIONALES TO PRY2205_ROL_C;

-- Sinonimos publicos caso 3
CREATE PUBLIC SYNONYM SYN_EMPRESA FOR PRY2205_EFT.EMPRESA;
CREATE PUBLIC SYNONYM SYN_ASESORIA FOR PRY2205_EFT.ASESORIA;

-- Grant a roles
GRANT SELECT ON PRY2205_EFT.PROFESIONAL TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.PROFESION TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.ISAPRE TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.TIPO_CONTRATO TO PRY2205_ROL_D;
GRANT SELECT ON PRY2205_EFT.RANGOS_SUELDOS TO PRY2205_ROL_D;

GRANT SELECT ON PRY2205_EFT.PROFESIONAL TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.PROFESION TO PRY2205_ROL_C;
GRANT SELECT ON PRY2205_EFT.ISAPRE TO PRY2205_ROL_C;


-- ===================
-- CASO 2 - USER DES
-- ===================

-- Generar el informe. La tabla ya esta creada por user EFT.
SHOW USER;

DELETE FROM SYN_CARTOLA_PROFESIONALES;
COMMIT;

INSERT INTO SYN_CARTOLA_PROFESIONALES (
  RUT_PROFESIONAL,
  NOMBRE_PROFESIONAL,
  PROFESION,
  ISAPRE,
  SUELDO_BASE,
  PORC_COMISION_PROFESIONAL,
  VALOR_TOTAL_COMISION,
  PORCENTATE_HONORARIO,
  BONO_MOVILIZACION,
  TOTAL_PAGAR
)
SELECT
  p.RUTPROF                                                         AS RUT_PROFESIONAL,
  INITCAP(p.NOMPRO || ' ' || p.APPPRO || ' ' || p.APMPRO)           AS NOMBRE_PROFESIONAL,
  pr.NOMPROFESION                                                   AS PROFESION,
  i.NOMISAPRE                                                       AS ISAPRE,
  ROUND(p.SUELDO,0)                                                 AS SUELDO_BASE,

  NVL(p.COMISION,0)                                                 AS PORC_COMISION_PROFESIONAL,
  ROUND(p.SUELDO * NVL(p.COMISION,0),0)                             AS VALOR_TOTAL_COMISION,

  /* Honorario según rango de sueldos (Tabla RANGOS_SUELDOS) */
  ROUND(p.SUELDO * NVL(r.HONOR_PCT, 0) / 100, 0)                             AS PORCENTATE_HONORARIO,

  /* Bono movilización fijo según tipo de contrato (según enunciado) */
  CASE UPPER(tc.NOMTCONTRATO)
    WHEN 'INDEFINIDO JORNADA COMPLETA' THEN 150000
    WHEN 'INDEFINIDO JORNADA PARCIAL'  THEN 120000
    WHEN 'PLAZO FIJO'                  THEN 60000
    WHEN 'HONORARIOS'                  THEN 50000
    ELSE 0
  END                                                               AS BONO_MOVILIZACION,

  /* Total a pagar */
  ROUND(
      p.SUELDO
    + (p.SUELDO * NVL(p.COMISION,0))
    + ROUND(p.SUELDO * NVL(r.HONOR_PCT, 0) / 100, 0)
    + (CASE UPPER(tc.NOMTCONTRATO)
         WHEN 'INDEFINIDO JORNADA COMPLETA' THEN 150000
         WHEN 'INDEFINIDO JORNADA PARCIAL'  THEN 120000
         WHEN 'PLAZO FIJO'                  THEN 60000
         WHEN 'HONORARIOS'                  THEN 50000
         ELSE 0
       END)
  ,0)                                                               AS TOTAL_PAGAR
FROM
  SYN_PROFESIONAL p
  JOIN SYN_PROFESION pr   ON pr.IDPROFESION = p.IDPROFESION
  JOIN SYN_ISAPRE i       ON i.IDISAPRE    = p.IDISAPRE
  LEFT JOIN SYN_TIPO_CONTRATO tc ON tc.IDTCONTRATO = p.IDTCONTRATO
  LEFT JOIN SYN_RANGOS_SUELDOS r
    ON p.SUELDO BETWEEN r.S_MIN AND r.S_MAX
ORDER BY
  pr.NOMPROFESION ASC,
  p.SUELDO DESC,
  NVL(p.COMISION,0) ASC,
  p.RUTPROF ASC;

COMMIT;

-- Consultar el informe 
SELECT *
FROM SYN_CARTOLA_PROFESIONALES
ORDER BY PROFESION, SUELDO_BASE DESC,
PORC_COMISION_PROFESIONAL, RUT_PROFESIONAL;


-- ===================
-- CASO 2 - USER CON
-- ===================

SHOW USER;

SELECT *
FROM SYN_CARTOLA_PROFESIONALES
ORDER BY PROFESION, SUELDO_BASE DESC,
PORC_COMISION_PROFESIONAL, RUT_PROFESIONAL;


-- ====================
-- CASO 3.1 - USER EFT
-- ====================

-- Creacion de la vista
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT
  /* RUT con DV */
  REPLACE(
      TO_CHAR(e.RUT_EMPRESA, 'FM99G999G999'),
      ',',
      '.'
  ) || '-' || e.DV_EMPRESA AS RUT_EMPRESA,


  /* Nombre en mayúscula (como tu ejemplo) */
  UPPER(e.NOMEMPRESA)                                                     AS NOMBRE_EMPRESA,

  /* IVA */
  e.IVA_DECLARADO                                                         AS IVA,

  /* Años existencia */
  TRUNC(MONTHS_BETWEEN(SYSDATE, e.FECHA_INICIACION_ACTIVIDADES) / 12)      AS ANIOS_EXISTENCIA,

  /* Total asesorías anuales (año anterior) */
  COUNT(*)                                                                AS TOTAL_ASESORIAS_ANUALES,

  /* Devolución IVA (según regla: IVA * (promedio mensual/100) ) */
  ROUND(e.IVA_DECLARADO * ((COUNT(*)/12)/100), 0)                         AS DEVOLUCION_IVA,

  /* Tipo cliente según promedio mensual */
  CASE
    WHEN (COUNT(*)/12) > 5 THEN 'CLIENTE PREMIUM'
    WHEN (COUNT(*)/12) BETWEEN 3 AND 5 THEN 'CLIENTE'
    ELSE 'CLIENTE POCO CONCURRIDO'
  END                                                                     AS TIPO_CLIENTE,

  /* “Corresponde” (promoción/recomendación) */
  CASE
    WHEN (COUNT(*)/12) > 5 AND COUNT(*) >= 7
      THEN '1 ASESORIA GRATIS'
    WHEN (COUNT(*)/12) > 5 AND COUNT(*) < 7
      THEN '1 ASESORIA 40% DE DESCUENTO'
    WHEN (COUNT(*)/12) BETWEEN 3 AND 5 AND COUNT(*) = 5
      THEN '1 ASESORIA 30% DE DESCUENTO'
    WHEN (COUNT(*)/12) BETWEEN 3 AND 5 AND COUNT(*) < 5
      THEN '1 ASESORIA 20% DE DESCUENTO'
    ELSE 'CAPTAR CLIENTE'
  END                                                                     AS CORRESPONDE
FROM
  SYN_EMPRESA e
  JOIN SYN_ASESORIA a
    ON a.IDEMPRESA = e.IDEMPRESA
WHERE
  /* Año anterior paramétrico */
  a.FIN >= ADD_MONTHS(TRUNC(SYSDATE, 'YYYY'), -12)
  AND a.FIN <  TRUNC(SYSDATE, 'YYYY')
GROUP BY
  e.RUT_EMPRESA,
  e.DV_EMPRESA,
  e.NOMEMPRESA,
  e.FECHA_INICIACION_ACTIVIDADES,
  e.IVA_DECLARADO;

COMMIT;

-- Mostrar la vista
SELECT *
FROM VW_EMPRESAS_ASESORADAS
ORDER BY NOMBRE_EMPRESA ASC;


-- Dar permiso al user CON
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;

-- Crear sinonimo publico para que acceda
CREATE PUBLIC SYNONYM SYN_VW_EMPRESAS_ASESORADAS
FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;

-- ===================
-- CASO 3.1 - USER CON
-- ===================

SELECT *
FROM SYN_VW_EMPRESAS_ASESORADAS
ORDER BY NOMBRE_EMPRESA;

-- ====================
-- CASO 3.2 - USER EFT
-- ====================

-- LIMPIEZA OPCIONAL
DROP INDEX IDX_ASESORIA_FIN_EMP;

-- Explicar plan del antes
EXPLAIN PLAN FOR
SELECT *
FROM SYN_VW_EMPRESAS_ASESORADAS
ORDER BY NOMBRE_EMPRESA;

-- Mostrar
SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);

-- Crear indice, ayuda a filtrar por fecha
-- Disclaimer: Hacer filtro por empresa no tiene sentido,
-- ya que la consulta pide todas las empresas.

CREATE INDEX IDX_ASESORIA_FIN_EMP
ON ASESORIA (FIN, IDEMPRESA);


-- Explicar plan del después
EXPLAIN PLAN FOR
SELECT *
FROM SYN_VW_EMPRESAS_ASESORADAS
ORDER BY NOMBRE_EMPRESA;

-- Mostrar
SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);
