/* ===========================================================
   LIMPIEZA SEGURA DE TABLAS Y SECUENCIAS 
   =========================================================== */
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ASIGNACION_TURNO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ORDEN_MANTENCION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MAQUINA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TIPO_MAQUINA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TURNO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TECNICO_MANT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE OPERARIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE JEFE_TURNO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMPLEADO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CAT_SALUD CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CAT_AFP CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PLANTA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE COMUNA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE REGION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REGION';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

/* ===========================================================
   CREACIÓN DE TABLAS
   =========================================================== */

CREATE TABLE REGION (
    id_region   NUMBER(4),
    nom_region  VARCHAR2(50) NOT NULL,
    CONSTRAINT REGION_PK PRIMARY KEY (id_region),
    CONSTRAINT UQ_NOM_REGION UNIQUE (nom_region)
);


CREATE TABLE COMUNA (
    id_comuna  NUMBER(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1050 INCREMENT BY 5),
    nom_comuna VARCHAR2(50) NOT NULL,
    id_region NUMBER(4) NOT NULL,
    CONSTRAINT COMUNA_PK PRIMARY KEY (id_comuna),
    CONSTRAINT FK_COMUNA_REGION FOREIGN KEY (id_region) REFERENCES REGION(id_region)
);


CREATE TABLE PLANTA (
    id_planta   NUMBER(7) GENERATED BY DEFAULT AS IDENTITY,
    nom_planta      VARCHAR2(50) NOT NULL,
    direccion   VARCHAR2(50) NOT NULL,
    id_comuna   NUMBER(4) NOT NULL,
    CONSTRAINT PLANTA_PK PRIMARY KEY (id_planta),
    CONSTRAINT FK_PLANTA_COMUNA FOREIGN KEY (id_comuna) REFERENCES COMUNA (id_comuna)
);

CREATE TABLE CAT_AFP (
    id_afp   NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    nom_afp   VARCHAR2(25) NOT NULL,
    CONSTRAINT AFP_PK PRIMARY KEY (id_afp),
    CONSTRAINT UQ_NOM_AFP UNIQUE (nom_afp)
);

CREATE TABLE CAT_SALUD (
    id_salud   NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    nom_salud   VARCHAR2(25) NOT NULL,
    CONSTRAINT SALUD_PK PRIMARY KEY (id_salud),
    CONSTRAINT UQ_NOM_SALUD UNIQUE (nom_salud)
);


CREATE TABLE EMPLEADO (
    id_empleado  NUMBER(12) GENERATED BY DEFAULT AS IDENTITY,
    rut_emp      VARCHAR2(12) NOT NULL,
    pnombre      VARCHAR2(25) NOT NULL,
    snombre      VARCHAR2(25),
    papellido    VARCHAR2(25) NOT NULL,
    sapellido    VARCHAR2(25) NOT NULL,
    fecha_contratacion DATE NOT NULL,
    sueldo_base        NUMBER(10) NOT NULL CHECK (SUELDO_BASE > 0),
    activo             CHAR(1) DEFAULT 'S' NOT NULL CHECK (ACTIVO IN ('S','N')),
    id_planta          NUMBER(7) NOT NULL,
    id_jefe            NUMBER(12) NULL,
    id_afp             NUMBER(5) NOT NULL,
    id_salud           NUMBER(5) NOT NULL,
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (id_empleado),
    CONSTRAINT UQ_EMPLEADO_RUT UNIQUE (rut_emp),
    CONSTRAINT FK_EMPLEADO_PLANTA FOREIGN KEY (id_planta) REFERENCES PLANTA (id_planta),
    CONSTRAINT FK_EMPLEADO_AFP FOREIGN KEY (id_afp) REFERENCES CAT_AFP (id_afp),
    CONSTRAINT FK_EMPLEADO_SALUD FOREIGN KEY (id_salud) REFERENCES CAT_SALUD (id_salud)
);


CREATE TABLE JEFE_TURNO (
    id_jefe NUMBER(12),
    area_responsabilidad VARCHAR2(50) NOT NULL,
    max_operarios_turno  NUMBER(3) NOT NULL CHECK (MAX_OPERARIOS_TURNO >= 0),
    CONSTRAINT JEFE_EMPLEADO_PK PRIMARY KEY (id_jefe),
    CONSTRAINT FK_JEFE_TURNO_EMPLEADO FOREIGN KEY (id_jefe) REFERENCES EMPLEADO (id_empleado)
);

ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMPLEADO_JEFE_TURNO FOREIGN KEY (id_jefe) REFERENCES JEFE_TURNO (id_jefe);

CREATE TABLE OPERARIO (
    id_operario NUMBER(12),
    categoria_proceso VARCHAR2(20)  NOT NULL,     -- CALIENTE / FRIO / INSPECCION
    certificacion     VARCHAR2(30),              
    horas_std_turno   NUMBER(2) DEFAULT 8 NOT NULL CHECK (HORAS_STD_TURNO > 0),
    CONSTRAINT OPERARIO_PK PRIMARY KEY (id_operario),
    CONSTRAINT FK_OPERARIO_EMPLEADO FOREIGN KEY (id_operario) REFERENCES EMPLEADO (id_empleado)
);

CREATE TABLE TECNICO_MANT (
    id_tecnico NUMBER(12),
    especialidad     VARCHAR2(20)  NOT NULL,  -- ELECTRICA / MECANICA / INSTRUMENTACION
    nivel_certificacion  VARCHAR2(30),          
    tiempo_resp_std_min  NUMBER(3) NOT NULL,  
    CONSTRAINT TECNICO_MANT_PK PRIMARY KEY (id_tecnico),
    CONSTRAINT FK_TECNICO_EMPLEADO FOREIGN KEY (id_tecnico) REFERENCES EMPLEADO (id_empleado)
);


CREATE TABLE TIPO_MAQUINA (
    id_tipo_maquina NUMBER(7) GENERATED BY DEFAULT AS IDENTITY,
    nom_tipo        VARCHAR2(50) NOT NULL,
    descripcion     VARCHAR2(200),
    CONSTRAINT TIPO_MAQ_PK PRIMARY KEY (id_tipo_maquina),
    CONSTRAINT UQ_NOM_TIPO UNIQUE (nom_tipo)
);

CREATE TABLE MAQUINA (
    id_planta       NUMBER(7) NOT NULL,
    num_maquina     NUMBER(7) NOT NULL,
    nom_maquina     VARCHAR2(50) NOT NULL,
    activo          CHAR(1) DEFAULT 'S' NOT NULL CHECK (ACTIVO IN ('S','N')),
    id_tipo_maquina NUMBER(7) NOT NULL,
    CONSTRAINT MAQUINA_PK PRIMARY KEY (id_planta, num_maquina),
    CONSTRAINT FK_MAQUINA_PLANTA FOREIGN KEY (id_planta) REFERENCES PLANTA (id_planta),
    CONSTRAINT FK_MAQUINA_TIPO FOREIGN KEY (id_tipo_maquina) REFERENCES TIPO_MAQUINA (id_tipo_maquina)
);

CREATE TABLE TURNO (
    id_turno     VARCHAR(7),
    nom_turno    VARCHAR2(20) NOT NULL,
    hora_inicio  CHAR(5) NOT NULL,
    hora_termino CHAR(5) NOT NULL,
    CONSTRAINT PK_TURNO PRIMARY KEY (id_turno),
    CONSTRAINT UQ_NOM_TURNO UNIQUE (nom_turno),
    CONSTRAINT CK_TURNO_HORA_INICIO CHECK (REGEXP_LIKE(hora_inicio , '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT CK_TURNO_HORA_TERMINO CHECK (REGEXP_LIKE(hora_termino, '^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'))
);


CREATE TABLE ORDEN_MANTENCION (
    id_orden          NUMBER(7) GENERATED BY DEFAULT AS IDENTITY,
    id_planta         NUMBER(7) NOT NULL,
    num_maquina       NUMBER(7) NOT NULL,
    id_tecnico       NUMBER(12) NOT NULL,
    fecha_programada   DATE NOT NULL,
    fecha_ejecucion    DATE,
    descripcion      VARCHAR2(200) NOT NULL,
    CONSTRAINT ORDEN_MANT_PK PRIMARY KEY (id_orden),
    CONSTRAINT FK_OM_MAQUINA FOREIGN KEY (id_planta, num_maquina) REFERENCES MAQUINA (id_planta, num_maquina),
    CONSTRAINT FK_OM_TECNICO FOREIGN KEY (id_tecnico) REFERENCES TECNICO_MANT (id_tecnico),
    CONSTRAINT CK_OM_FECHAS CHECK (fecha_ejecucion IS NULL OR fecha_ejecucion >= fecha_programada)
);


CREATE TABLE ASIGNACION_TURNO (
    id_asignacion NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    fecha_asig    DATE NOT NULL,
    id_empleado   NUMBER(12) NOT NULL,
    id_turno      VARCHAR(7) NOT NULL,
    id_planta     NUMBER(7) NOT NULL,
    num_maquina   NUMBER(7) NOT NULL,
    rol           VARCHAR2(50),
    CONSTRAINT PK_ASIG_TURNO PRIMARY KEY (id_asignacion),
    CONSTRAINT UQ_ASIG_EMPLEADO_FECHA UNIQUE (id_empleado,fecha_asig),
    CONSTRAINT FK_ASIG_EMPLEADO FOREIGN KEY (id_empleado) REFERENCES EMPLEADO (id_empleado),
    CONSTRAINT FK_ASIG_TURNO FOREIGN KEY (id_turno) REFERENCES TURNO (id_turno),
    CONSTRAINT FK_ASIG_MAQUINA FOREIGN KEY (id_planta, num_maquina) REFERENCES MAQUINA (id_planta, num_maquina)
);

/* ===========================================================
    POBLAMIENTO 
   =========================================================== */
   
CREATE SEQUENCE SEQ_REGION START WITH 21 INCREMENT BY 1;
INSERT INTO REGION (id_region, nom_region) VALUES (SEQ_REGION.NEXTVAL, 'Región de Valparaíso');
INSERT INTO REGION (id_region, nom_region) VALUES (SEQ_REGION.NEXTVAL, 'Región Metropolitana');

INSERT INTO COMUNA (nom_comuna, id_region) VALUES ('Quilpué', 21);
INSERT INTO COMUNA (nom_comuna, id_region) VALUES ('Maipú', 22);

INSERT INTO PLANTA (id_planta, nom_planta, direccion, id_comuna) VALUES (45, 'Planta Oriente', 'Camino Industrial 1234', 1050);
INSERT INTO PLANTA (id_planta, nom_planta, direccion, id_comuna) VALUES (46, 'Planta Costa', 'Av. Vidrieras 890', 1055);


INSERT INTO TURNO (id_turno, nom_turno, hora_inicio, hora_termino) VALUES ('M0715', 'Mañana', '07:00', '15:00');
INSERT INTO TURNO (id_turno, nom_turno, hora_inicio, hora_termino) VALUES ('N2307', 'Noche', '23:00', '07:00');
INSERT INTO TURNO (id_turno, nom_turno, hora_inicio, hora_termino) VALUES ('T1523', 'Tarde', '15:00', '23:00');


/* ===========================================================
    INFORME 1 
   =========================================================== */
   
SELECT
  id_turno || ' - ' || nom_turno       AS TURNO,
  hora_inicio  AS ENTRADA,
  hora_termino AS SALIDA
FROM turno
WHERE hora_inicio > '20:00'
ORDER BY hora_inicio DESC;

/* ===========================================================
    INFORME 2 
   =========================================================== */
   
SELECT
  id_turno || ' - ' || nom_turno    AS TURNO,
  hora_inicio  AS ENTRADA,
  hora_termino AS SALIDA
FROM turno
WHERE hora_inicio BETWEEN '06:00' AND '14:59'
ORDER BY hora_inicio ASC;
